version: "1.0"

services:
  library_api:
    build:
      context: .
    command:
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - library_db

  redis:
    image: "redis:alpine"

  library_db:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
  
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A library_service worker -l INFO"
    depends_on:
      - library_api
      - redis
      - library_db
    restart: on-failure
    env_file:
      - .env

  celery-beat:
    build: 
      context: .
      dockerfile: Dockerfile
    command: "celery -A library_service  beat -l INFO"
    depends_on:
      - library_api
      - redis
      - library_db
    restart: on-failure
    env_file:
      - .env
