# Generated by Django 4.1.4 on 2022-12-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="money_to_pay",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
