# Generated by Django 4.1.4 on 2022-12-31 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0002_alter_borrow_actual_return_date"),
        ("payment", "0002_alter_payment_money_to_pay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="borrowing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="borrowing.borrow",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
