# Generated by Django 4.1.4 on 2022-12-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="actual_return_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
